### PR TITLE
Add "mobile" to Users table

### LINKED ISSUE #121: Databases: Insert "Mobile" field in the User table in DB
## User story
**Who:** **As a** developer
**What:** **I want to** have a field in the user's table for the user's 'Mobile'.
**Why:** **so that I can** add it to the User_ id api endpoint,  so I can be able to show in the User info in the profile page.
## Acceptance criteria
This is how it's supposed to look on the profile page

user-info

## Implementation details

Read the following documentation for inspiration https://gist.github.com/NigelEarle/70db130cc040cc2868555b29a0278261

### PR DESCRIPTION
**Pull request by m-elshawa**
# Description

mobile field added to users table

Fixes # (121)

# How to test?

Check DB, users table if the mobile field exists

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [x] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [x] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Comment by Infamou5** [comment]
As a side note I already added it in this PR:
https://github.com/HackYourFuture-CPH/fp-class19/tree/Fix-Image-Links/src/server
You can just copy paste migration and seed files.

**Comment by Impressiv3** [comment]
image

**Comment by Impressiv3** [comment]
I can see the mobile table added to user but when I run this branch it won't even run.

**Comment by m-elshawa** [comment]
This PR was resolved on PR #176

**Pull request closed without merging**
