### PR TITLE
 seeding in favorite table

### LINKED ISSUE #124: Databases: Favorites table(seeds)
## User story
**Who:** **As a** developer
**What:** **I want to** create/add the Favorite products for the users in favorite table.
**Why:** **so that I can** save and mock data.
## Acceptance criteria
favorites table have been created with all the required fields. ( migration and seed files can be run from the command line using Knex )

image
##Implementation Details
Create a favorite-table file with seed entries in src/server/seeds/development

### PR DESCRIPTION
**Pull request by hparul**
# Description

This PR is about creating seeds in favorites table so that favorite product of a user is shown

Fixes # 124

# How to test?

Please provide a short summary how your changes can be tested?
Run npm run db:setup

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [x] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [x] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by nataliasowa — COMMENTED** [review]
Works on my machine. I think you've accidentally created 2 exact same files. Could you remove one? :)

**Review by Divyajg — APPROVED** [review]
It's working on my machine. 👍

**Review by Impressiv3 — APPROVED** [review]

**Comment by Impressiv3** [comment]
Tested it on my local. LGTM
image

**Comment by Impressiv3** [comment]
Tested reviewed approved by 2+

**Pull request merged**
