### PR TITLE
Forgot password page

### LINKED ISSUE #163: Frontend: Forgot password page container
**Who**: As a developer
**What**: I want to develop Forgot password page container.
**Why**: So that the user can have the possibility to recover their password.

## Acceptance criteria
This page should look according to screenshot below:

image

## Implementation details

You will need to include in the ForgotPasswordPage.Container the components and elements for:

Recover Password Component - [issue#95](https://github.com/HackYourFuture-CPH/fp-class19/issues/95) already merged

Use the container and style file mentioned on this [issue#32](https://github.com/HackYourFuture-CPH/fp-class19/issues/32)

### PR DESCRIPTION
**Pull request by Divyajg**
# Description

Forgot Password Page

Fixes # (163)

# How to test?

Pull the branch
npm run dev
go to Login Page and click on forgotpassword

# Checklist

- [✔ ] I have performed a self-review of my code
[✔ ] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you doubt, check the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [✔ ] I have commented on my code, particularly in hard-to-understand areas, if your code was simple enough mark the box anyway
- [ ✔] I have made corresponding changes to the documentation, if your code was simple enough mark the box anyway
- [✔ ] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Comment by suvarna-ratna** [comment]
change  file name  Container.js to container.js

**Comment by suvarna-ratna** [comment]
working fine .

**Review by suvarna-ratna — APPROVED** [review]
working fine

**Review by santhoshboinapally — APPROVED** [review]
Looking good

**Review by FlorentinaPetica — APPROVED** [review]

**Comment by Impressiv3** [comment]
Already 3+ approved reviews.
Merge it.

**Pull request merged**
