### PR TITLE
Get favourite endpoint

### LINKED ISSUE #26: Endpoint to Get favorite products from Users
Who: As a developer
What: I want to be able to get all favorite products of specific user
Why: so that we can show it in to the user on the Favorites page

Acceptance criteria
-------------------------
The endpoint needs to return a result that allows the frontend to display favorite products as below in the red box:
image

Implementation details
---------------------------
Create the GET endpoint for 'api/users/{user_id}/favorites'

### PR DESCRIPTION
**Pull request by FlorentinaPetica**
# Description

Created an endpoint to get all favorites products for specified user.

Fixes #26

# How to test?

Pull the Branch, 
Go to your db and insert a row into table favourites,
Run: npm run dev ,
Check endpoint like [http://localhost:3000/api/user/user_id/favorites
go to: [http://localhost:3000/api/documentation] to check swagger documentation for the endpoint,

image

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [x] I have commented on my code, particularly in hard-to-understand areas, if your code was simple enough mark the box anyway
- [x] I have made corresponding changes to the documentation, if your code was simple enough mark the box anyway
- [x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by m-elshawa — APPROVED** [review]
I tested on swagger and I can see the favorites endpoint. and on localhost all works fine :)

**Review by Divyajg — APPROVED** [review]
It's working on my machine as it should. 👍

**Review by senner007 — CHANGES_REQUESTED** [review]
Same git issue as #80

**Review by santhoshboinapally — APPROVED** [review]
I checked on swagger and I can see the favorites endpoint. and on localhost, works fine :)

**Pull request merged**
