### PR TITLE
Storybook: Header component 

### LINKED ISSUE #4: Storybook: Header component
## User story

**Who:** **As a** developer
**What:** **I want to** be have a Header component where can have Logo, shopping cart, favourite heart, login icon and text.
**Why:** **so that I can** have the same component in multiple pages for multiple scenarios

## Acceptance criteria

Create a Storybook component like the one we can see below where we can see both scenarios:
 
image

image

Check the wireframes here: https://www.figma.com/file/yo4QT2EcPo83HAMI3ydMxb/HYF-Wireframes?node-id=4%3A1324

## Implementation details

Download the images from the wireframes and add them to this folder src/client/assets/images

### PR DESCRIPTION
**Pull request by nataliasowa**
# Description

I've created the Header component with Logo, shopping cart, favorite heart, login icon and text it display (such as 'Log in' and 'Hello {username}').

Fixes #4 

# How to test?

npm run storybook

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [x] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [x] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Comment by nataliasowa** [comment]
Please disregard these two first commits as they belong to another branch. 

Screenshot 2022-01-28 at 16 59 56

**Comment by senner007** [comment]
> Please disregard these two first commits as they belong to another branch.
> 
> Screenshot 2022-01-28 at 16 59 56

Hi. @NataliaS1994 

Remember to create your branch off of develop - always. 
So 
```
git checkout develop
git pull
git checkout -b feature/<branchname>

```
Otherwise we spent too much time untangling things

**Review by dpfernandes — CHANGES_REQUESTED** [review]
Please remove Database files from this PR.

**Review by pankaj28843 — APPROVED** [review]
Looks good to me!

**Pull request merged**
