### PR TITLE
Feature/discount products

### LINKED ISSUE #83: Backend: Get the list of products that have discount
Who: As a developer
What: I want to be able to get all the products that have discount
Why: so that we can provide a list of discount products on the special offer page.

Acceptance criteria
-------------------------
The endpoint needs to return a result that allows the frontend to display discounted products as below :

image

Implementation details
---------------------------
Create the GET endpoint for 'api/products/on_discount'

### PR DESCRIPTION
**Pull request by Divyajg**
# Description

This endpoint provides the list of products having discount.

Fixes # (83)

# How to test?

Pull the branch
run: npm run dev
Check on swagger.

# Checklist

- [✔ ] I have performed a self-review of my own code
- [✔ ] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [ ✔] I have commented on my code, particularly in hard-to-understand areas, if your code was simple enough mark the box anyway
- [✔ ] I have made corresponding changes to the documentation, if your code was simple enough mark the box anyway
- [✔ ] This PR is ready to be merged and not breaking any other functionality

image

### CODE REVIEW

**Review by m-elshawa — COMMENTED** [review]
Hi Divya,
This branch has the same problem I had before, did you remember to pull before you create it? it gives me the following message
discount-products

**Review by santhoshboinapally — APPROVED** [review]
Its working on machine.

**Review by hparul — COMMENTED** [review]
backend running fine but npm run dev is giving all 24 products.

**Comment by Divyajg** [comment]
> backend running fine but npm run dev is giving all 24 products.

I think you were trying get all products.
For discount products it will show products from 17 to 24

**Comment by suvarna-ratna** [comment]
Working fine , getting discount products .

**Review by suvarna-ratna — APPROVED** [review]

**Comment by nataliasowa** [comment]
Checked the backend and it works well!

**Pull request merged**
