### PR TITLE
Frontend: Product sorting 

### LINKED ISSUE #8: Frontend: Product sorting
## User story

**Who:** **As a** Developer
**What:** **I want to** be have a Product Sorting component where can sort the displayed products in different ways
**Why:** **so that I can** then show then as the user prefers to see them

## Acceptance criteria

Create a React component like the one we can see below where we can see both scenarios:
 
Screen Shot 2022-01-20 at 10 59 04

Check the wireframes here: https://www.figma.com/file/yo4QT2EcPo83HAMI3ydMxb/HYF-Wireframes?node-id=4%3A1324

## Implementation details

N/A

### PR DESCRIPTION
**Pull request by suvarna-ratna**
# Description
It is a Product Sorting component where user can sort the displayed products in different ways.. so that user can view how he/she would like to see.
Please provide a short summary explaining what this PR is about.

Fixes  #8

# How to test?
npm run storybook
Please provide a short summary how your changes can be tested?

# Checklist

- [X] I have performed a self-review of my own code
- [x] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [X] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [X] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [X] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by senner007 — CHANGES_REQUESTED** [review]
Hi.
If you look at the readme you can see that the frontend is divided into 

- presentational components and
- container components  

This allows for a clean separation of logic/stateful and visual/stateless.

Another way of thinking about this is to say that a component must only have one responsibility. Here the component both does the sorting and and displays it.

**Comment by suvarna-ratna** [comment]
> Hi. If you look at the readme you can see that the frontend is divided into
> 
> * presentational components and
> * container components
> 
> This allows for a clean separation of logic/statefull and visual/stateless.
> 
> Another way of thinking about this is to say that a component must only have one responsibility. Here the component both does the sorting and and displays it.

Okay @senner007 .. Thank you .. updated by removing displaying products..

**Review by senner007 — APPROVED** [review]
Great ! 👍
I would in fact go further and create a stateful sort container with stateless sort list and elements.

```
<SortContainer>
   <SortList>
     <Sorter type= 'AlphabeticallyAZ'>
     <Sorter type= 'AlphabeticallyZA'>
     <Sorter type= 'PriceDescending'>
     <Sorter type= 'PriceAscending'>
   </SortList>
</SortContainer>

```
But we can also leave that for now.

You could create an issue for the Products component and Products Container component if you wish. The ProductContainer would then contain the state with the sorted products and the SortContainer would call back to update the state causing the products to rerender.

```
<ProductContainer>
   </SortContainer>
   </Products>
</ProductContainer>
```

At least thats how I view it as of now.

**Comment by suvarna-ratna** [comment]
> Great ! 👍 I would in fact go further and create a stateful sort container with stateless sort list and elements.
> 
> ```
> <SortContainer>
>    <SortList>
>      <Sorter type= 'AlphabeticallyAZ'>
>      <Sorter type= 'AlphabeticallyZA'>
>      <Sorter type= 'PriceDescending'>
>      <Sorter type= 'PriceAscending'>
>    </SortList>
> </SortContainer>
> ```
> 
> But we can also leave that for now.
> 
> You could create an issue for the Products component and Products Container component if you wish. The ProductContainer would then contain the state with the sorted products and the SortContainer would call back to update the state causing the products to rerender.
> 
> ```
> <ProductContainer>
>    </SortContainer>
>    </Products>
> </ProductContainer>
> ```
> 
> At least thats how I view it as of now.

Okay ..Thank you Niels..
I have created issues 43 and 44 for displaying products and sort displayed products.. But i need to wait for product component..

**Pull request merged**
