### PR TITLE
Frontend: Special Offer Banner Component

### LINKED ISSUE #21: Frontend: Special Offer Banner Component
## User story

**Who:** **As a** developer
**What:** **I want to** have a Special Offer Banner component to be able to display it on the Landing Page.
**Why:** **so that I can** create a link for the users to see the Special Offers page.

## Acceptance criteria

Create a React component like the one we can see below

image

Check the wireframes here: https://www.figma.com/file/yo4QT2EcPo83HAMI3ydMxb/HYF-Wireframes?node-id=4%3A1324

## Implementation details

Download the image from the wireframes and add them to this folder src/client/assets/images

Add a folder called fonts under assets - /src/client/assets/ and add the font files.

### PR DESCRIPTION
**Pull request by santhoshboinapally**
# Description
Special Offer Banner component to be able to display it on the Landing Page. Created a link for the users to see the Special Offers page. It should display only on landing page we have to add this React Component in Home.js file
Fixes # (21)

# How to test?
By running `npm run dev`
Please provide a short summary how your changes can be tested?

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [x] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [x] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by senner007 — CHANGES_REQUESTED** [review]
This has has changes from #23.
Please remember to create your branches from develop
See here #42

Let us know if you need help with git

**Comment by santhoshboinapally** [comment]
> This has has changes from #23. Please remember to create your branches from develop See here #42
> 
> Let us know if you need help with git

HI Should I remove this PR and create new one with the branch created from develop.

**Comment by senner007** [comment]
> HI Should I remove this PR and create new one with the branch created from develop.

I think so, alternatively the first branch is merged first and then you merge develop into this one. 
But yes, its cleaner

**Comment by santhoshboinapally** [comment]
> > HI Should I remove this PR and create new one with the branch created from develop.
> 
> I think so, alternatively the first branch is merged first and then you merge develop into this one. But yes, its cleaner

I created a new pull request "Frontend: Special Offer Banner Component #55" . should i close this one

**Pull request closed without merging**
